In [1]:
import numpy as np
from relife2 import SurvivalData

In [2]:
def show_data(data : SurvivalData):
    data.info()

    print("\n")
    print("lifetimes:\n", data.lifetimes)

    print("\n")
    print("observed lifetimes index:\n", data.observed())
    print("observed lifetimes values:\n", data.observed(return_values=True))
    print("\n")
    print("left censored index:\n", data.censored(how="left"))
    print("left censored values:\n", data.censored(return_values=True, how="left"))
    print("\n")
    print("right censored  index:\n", data.censored(how="right"))
    print("right censored  values:\n", data.censored(return_values=True, how="right"))
    print("\n")
    print("interval censored index:\n", data.censored(how="interval"))
    print("interval censored values:\n", data.censored(return_values=True, how="interval"))

    print("left truncated index:\n", data.truncated(how="left"))
    print("left truncated values:\n", data.truncated(return_values=True, how="left"))
    print("\n")
    print("right truncated  index:\n", data.truncated(how="right"))
    print("right truncated  values:\n", data.truncated(return_values=True, how="right"))
    print("\n")
    print("interval truncated index:\n", data.truncated(how="interval"))
    print("interval truncated values:\n", data.truncated(return_values=True, how="interval"))

# 1D lifetime values

In [3]:
time = np.random.randint(10, high=50, size=100)
data = SurvivalData(time)
show_data(data)

     Lifetime data            Counts
              Tot.               100
          Observed               100
     Left censored                 0
    Right censored                 0
 Interval censored                 0
    Left truncated                 0
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [39 47 23 47 46 33 33 32 30 22 36 49 40 21 43 27 25 43 14 45 36 13 15 10
 16 32 44 25 44 17 19 16 11 17 12 20 39 34 25 10 40 35 21 24 26 14 37 19
 41 24 38 32 15 12 33 15 35 19 29 36 41 28 37 25 24 42 45 18 19 39 49 47
 34 35 41 43 45 33 20 26 49 11 35 34 38 35 45 46 46 11 35 42 43 38 45 33
 39 26 10 34]


observed lifetimes index:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
observed lif

In [4]:
time = np.random.randint(10, high=50, size=100)
event = np.random.randint(0, 2, size=100)
data = SurvivalData(time, event=event)
show_data(data)

     Lifetime data            Counts
              Tot.               100
          Observed                45
     Left censored                 0
    Right censored                55
 Interval censored                 0
    Left truncated                 0
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [19 13 17 43 43 15 17 39 40 23 41 41 22 11 48 37 49 41 27 47 41 26 11 13
 47 34 47 36 26 42 23 30 11 40 36 37 43 34 42 14 36 16 23 21 44 36 39 39
 10 10 30 44 38 21 21 19 37 14 13 47 34 28 44 26 15 41 46 45 47 21 36 47
 18 47 10 45 27 47 49 46 45 33 28 14 46 13 36 19 38 23 48 43 19 41 29 14
 25 11 10 48]


observed lifetimes index:
 [ 1  2  8  9 10 12 13 15 17 18 20 22 23 24 25 29 34 35 36 44 45 48 49 51
 52 53 54 58 59 60 64 69 73 76 77 80 82 84 87 88 89 90 95 98 99]
observed lifetimes values:
 [13 17 40 23 41 22 11 37 41 27 41 11 13 47 34 42 36 37 43 44 36 10 10 44
 38 21 21 13 47 34 15 21 47 27 47 45 28 46 19 38 23 48 14 10 48]


left censore

In [5]:
time = np.random.randint(21, high=50, size=100)
event = np.random.randint(0, 2, size=100)
entry = np.random.randint(10, high=20, size=100)
data = SurvivalData(time, event=event, entry=entry)
show_data(data)

     Lifetime data            Counts
              Tot.               100
          Observed                48
     Left censored                 0
    Right censored                52
 Interval censored                 0
    Left truncated               100
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [28 36 31 38 45 33 39 37 27 38 37 48 47 39 37 32 34 21 46 32 29 30 27 43
 30 44 40 25 40 23 44 43 35 22 22 36 44 37 27 42 31 47 29 36 49 33 30 41
 37 40 48 21 38 22 23 26 45 39 44 21 44 23 23 42 43 48 27 43 28 24 40 47
 39 45 31 45 44 47 27 21 40 36 30 40 21 44 41 27 22 32 29 27 29 23 41 38
 47 33 36 46]


observed lifetimes index:
 [ 0  4  7  9 10 12 13 15 16 17 18 20 23 25 26 27 31 33 38 40 44 45 46 47
 49 51 53 54 55 56 57 58 61 63 64 67 70 77 81 83 87 88 92 93 94 95 97 99]
observed lifetimes values:
 [28 45 37 38 37 47 39 32 34 21 46 29 43 44 40 25 43 22 27 31 49 33 30 41
 40 21 22 23 26 45 39 44 23 42 43 43 40 47 36 40 27 22 29 23 41 38 33 

# 2D lifetime values

In [6]:
time = np.array([
    [1,2],
    [0,4],
    [5,5],
    [7,np.inf],
    [10,10],
    [2,10],
    [10,11]
])
data = SurvivalData(time)
show_data(data)

     Lifetime data            Counts
              Tot.                 7
          Observed                 2
     Left censored                 1
    Right censored                 1
 Interval censored                 3
    Left truncated                 0
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [[ 1.  2.]
 [ 0.  4.]
 [ 5.  5.]
 [ 7. inf]
 [10. 10.]
 [ 2. 10.]
 [10. 11.]]


observed lifetimes index:
 [2 4]
observed lifetimes values:
 [ 5. 10.]


left censored index:
 [1]
left censored values:
 [4.]


right censored  index:
 [3]
right censored  values:
 [7.]


interval censored index:
 [0 5 6]
interval censored values:
 [[ 1.  2.]
 [ 2. 10.]
 [10. 11.]]
left truncated index:
 []
left truncated values:
 []


right truncated  index:
 []
right truncated  values:
 []


interval truncated index:
 []
interval truncated values:
 []
