In [1]:
import numpy as np
from relife2 import SurvivalData

In [2]:
def show_data(data : SurvivalData):
    data.info()
    print("\n")
    print("lifetimes:\n", data.lifetimes)
    print("\n")
    print("observed lifetimes index:\n", data.observed())
    print("observed lifetimes values:\n", data.observed(return_values=True))
    print("\n")
    print("left censored index:\n", data.censored(how="left"))
    print("left censored values:\n", data.censored(return_values=True, how="left"))
    print("\n")
    print("right censored  index:\n", data.censored(how="right"))
    print("right censored  values:\n", data.censored(return_values=True, how="right"))
    print("\n")
    print("interval censored index:\n", data.censored(how="interval"))
    print("interval censored values:\n", data.censored(return_values=True, how="interval"))

# 1D lifetime

In [3]:
time = np.random.randint(10, high=50, size=100)
data = SurvivalData(time)
show_data(data)

     Lifetime data            Counts
              Tot.               100
          Observed               100
     Left censored                 0
    Right censored                 0
 Interval censored                 0
    Left truncated                 0
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [48 42 22 44 36 14 48 13 18 27 29 48 25 48 27 22 15 27 19 16 32 30 45 48
 33 46 49 27 16 39 37 20 13 14 41 36 27 19 21 30 34 29 14 43 28 48 33 10
 12 22 29 15 40 43 31 22 18 34 37 19 34 20 14 16 45 25 13 23 18 47 35 18
 37 23 49 29 15 45 38 47 38 39 13 20 40 20 42 29 30 11 11 15 45 20 46 27
 40 11 46 28]


observed lifetimes index:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
observed lif

In [4]:
time = np.random.randint(10, high=50, size=100)
event = np.random.randint(0, 2, size=100)
data = SurvivalData(time, event=event)
show_data(data)

     Lifetime data            Counts
              Tot.               100
          Observed                56
     Left censored                 0
    Right censored                44
 Interval censored                 0
    Left truncated                 0
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [49 49 21 30 15 48 44 48 13 34 17 48 33 29 36 15 43 13 14 45 19 18 23 47
 30 13 13 39 19 37 30 33 16 13 13 28 44 14 16 28 49 35 28 40 15 36 36 32
 22 16 33 16 19 39 18 41 21 37 48 32 20 13 18 19 15 17 23 34 34 39 28 25
 15 11 38 38 19 11 25 45 30 44 32 24 27 42 10 26 35 29 36 16 25 34 21 39
 46 13 26 39]


observed lifetimes index:
 [ 0  1  4  5  6  7  9 11 14 18 19 21 22 23 24 25 26 27 29 30 31 36 37 38
 43 48 49 50 51 52 53 55 56 58 59 61 65 66 69 70 72 74 76 77 78 79 82 83
 84 86 87 89 90 93 94 99]
observed lifetimes values:
 [49 49 15 48 44 48 34 48 36 14 45 18 23 47 30 13 13 39 37 30 33 44 14 16
 40 22 16 33 16 19 39 41 21 48 32 13 17 23 39

In [5]:
print(event)

[1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 1
 1 1 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 0 1 1 0 1 0
 1 0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 0 0 1]


In [6]:
print(event)

[1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 1
 1 1 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 0 1 1 0 1 0
 1 0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 0 0 1]


In [7]:
time = np.random.randint(21, high=50, size=100)
event = np.random.randint(0, 2, size=100)
entry = np.random.randint(10, high=20, size=100)
data = SurvivalData(time, event=event, entry=entry)
show_data(data)

     Lifetime data            Counts
              Tot.               100
          Observed                48
     Left censored                 0
    Right censored                52
 Interval censored                 0
    Left truncated               100
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [28 48 47 37 29 45 21 40 30 34 37 22 22 43 34 40 34 31 44 33 34 39 33 37
 25 47 21 40 39 29 25 46 23 40 37 24 25 26 42 40 37 45 22 41 22 32 29 25
 27 45 38 21 39 49 22 40 44 23 45 49 37 35 40 35 28 29 39 31 29 29 43 43
 42 23 23 37 29 39 43 22 48 41 43 21 40 38 36 21 25 38 29 25 30 36 30 22
 36 28 21 27]


observed lifetimes index:
 [ 0  3  5  6  9 11 13 16 18 21 22 23 24 25 26 31 32 33 37 38 41 43 44 46
 48 49 51 52 56 58 59 61 62 65 68 71 72 74 75 76 80 84 85 86 88 89 95 99]
observed lifetimes values:
 [28 37 45 21 34 22 43 34 44 39 33 37 25 47 21 46 23 40 26 42 45 41 22 29
 27 45 21 39 44 45 49 35 40 29 29 43 42 23 37 29 48 40 38 36 25 38 22 

# 2D lifetime

In [8]:
time = np.array([
    [1,2],
    [0,4],
    [5,5],
    [7,np.inf],
    [10,10],
    [2,10],
    [10,11]
])
data = SurvivalData(time)
show_data(data)

     Lifetime data            Counts
              Tot.                 7
          Observed                 2
     Left censored                 1
    Right censored                 1
 Interval censored                 3
    Left truncated                 0
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [[ 1.  2.]
 [ 0.  4.]
 [ 5.  5.]
 [ 7. inf]
 [10. 10.]
 [ 2. 10.]
 [10. 11.]]


observed lifetimes index:
 [2 4]
observed lifetimes values:
 [ 5. 10.]


left censored index:
 [1]
left censored values:
 [4.]


right censored  index:
 [3]
right censored  values:
 [7.]


interval censored index:
 [0 5 6]
interval censored values:
 [[ 1.  2.]
 [ 2. 10.]
 [10. 11.]]
