In [1]:
import numpy as np
from relife2 import SurvivalData

In [2]:
def show_data(data : SurvivalData):
    data.info()
    print("\n")
    print("lifetimes:\n", data.lifetimes)
    print("\n")
    print("observed lifetimes index:\n", data.observed())
    print("observed lifetimes values:\n", data.observed(return_values=True))
    print("\n")
    print("left censored index:\n", data.censored(how="left"))
    print("left censored values:\n", data.censored(return_values=True, how="left"))
    print("\n")
    print("right censored  index:\n", data.censored(how="right"))
    print("right censored  values:\n", data.censored(return_values=True, how="right"))
    print("\n")
    print("interval censored index:\n", data.censored(how="interval"))
    print("interval censored values:\n", data.censored(return_values=True, how="interval"))

# 1D lifetime

In [3]:
time = np.random.randint(10, high=50, size=100)
data = SurvivalData(time)
show_data(data)

     Lifetime data            Counts
              Tot.               100
          Observed               100
     Left censored                 0
    Right censored                 0
 Interval censored                 0
    Left truncated                 0
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [11 32 44 32 30 27 31 19 39 48 17 23 33 38 24 28 41 49 35 22 36 15 44 47
 17 13 23 32 27 39 28 38 46 43 19 11 38 44 49 39 20 46 26 40 11 12 45 15
 48 29 40 15 33 43 49 44 24 11 10 45 33 31 40 20 12 43 39 12 21 48 48 19
 45 42 41 29 26 37 45 27 41 23 30 11 43 30 34 24 13 48 17 39 13 13 13 14
 25 43 11 24]


observed lifetimes index:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
observed lif

In [4]:
time = np.random.randint(10, high=50, size=100)
event = np.random.randint(0, 2, size=100)
data = SurvivalData(time, event=event)
show_data(data)

     Lifetime data            Counts
              Tot.               100
          Observed                51
     Left censored                49
    Right censored                 0
 Interval censored                 0
    Left truncated                 0
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [30 35 44 35 22 48 48 23 34 17 15 16 10 38 23 35 35 38 34 26 29 27 29 21
 23 14 21 17 27 19 24 33 26 20 23 38 23 49 13 12 46 12 13 23 49 10 45 14
 38 23 42 20 47 21 29 11 45 28 48 22 41 18 36 25 33 36 30 42 39 31 10 30
 35 33 17 16 45 28 33 48 32 13 31 23 12 26 24 42 47 36 39 13 45 38 21 15
 23 12 48 23]


observed lifetimes index:
 [ 0  1  9 12 13 14 19 21 22 23 24 25 26 27 28 29 34 37 40 41 42 44 45 47
 48 49 55 57 59 60 62 63 64 69 70 72 74 75 76 79 80 81 83 86 89 90 91 92
 94 98 99]
observed lifetimes values:
 [30 35 17 10 38 23 26 27 29 21 23 14 21 17 27 19 23 49 46 12 13 49 10 14
 38 23 11 28 22 41 36 25 33 31 10 35 17 16 45 48 32 13 23 24

In [5]:
print(event)

[1 1 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0
 1 0 0 1 1 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 0 0 0 0 1 1 0 1 0
 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 1 1 0 1 0 0 0 1 1]


In [6]:
print(event)

[1 1 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0
 1 0 0 1 1 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 0 0 0 0 1 1 0 1 0
 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 1 1 0 1 0 0 0 1 1]


In [7]:
time = np.random.randint(21, high=50, size=100)
event = np.random.randint(0, 2, size=100)
entry = np.random.randint(10, high=20, size=100)
data = SurvivalData(time, event=event, entry=entry)
show_data(data)

     Lifetime data            Counts
              Tot.               100
          Observed                47
     Left censored                53
    Right censored                 0
 Interval censored                 0
    Left truncated               100
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [38 24 40 37 41 43 31 35 25 47 21 43 33 46 26 24 34 22 36 32 24 47 47 24
 27 40 30 40 33 27 36 35 40 49 21 34 42 40 32 34 36 27 40 45 27 45 43 45
 22 39 21 32 45 40 33 24 25 33 26 27 27 37 47 48 35 35 38 48 29 43 39 46
 47 48 46 24 31 24 43 37 44 43 40 36 31 45 46 28 44 22 45 45 31 31 41 26
 22 29 42 26]


observed lifetimes index:
 [ 5  7  9 11 12 13 15 17 18 19 21 23 24 28 29 31 32 33 36 43 46 48 49 51
 53 57 58 60 61 62 64 68 69 73 77 80 81 83 86 87 88 89 91 92 93 97 99]
observed lifetimes values:
 [43 35 47 43 33 46 24 22 36 32 47 24 27 33 27 35 40 49 42 45 43 22 39 32
 40 33 26 27 37 47 35 29 43 48 24 44 43 36 46 28 44 22 45 31 31 29 26]




# 2D lifetime

In [8]:
time = np.array([
    [1,2],
    [0,4],
    [5,5],
    [7,np.inf],
    [10,10],
    [2,10],
    [10,11]
])
data = SurvivalData(time)
show_data(data)

     Lifetime data            Counts
              Tot.                 7
          Observed                 2
     Left censored                 1
    Right censored                 1
 Interval censored                 3
    Left truncated                 0
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [[ 1.  2.]
 [ 0.  4.]
 [ 5.  5.]
 [ 7. inf]
 [10. 10.]
 [ 2. 10.]
 [10. 11.]]


observed lifetimes index:
 [2 4]
observed lifetimes values:
 [ 5. 10.]


left censored index:
 [1]
left censored values:
 [4.]


right censored  index:
 [3]
right censored  values:
 [7.]


interval censored index:
 [0 5 6]
interval censored values:
 [[ 1.  2.]
 [ 2. 10.]
 [10. 11.]]
