In [1]:
import numpy as np
from relife2.data import SurvivalData

In [2]:
def show_data(data : SurvivalData):
    data.info()
    print("\n")
    print("lifetimes:\n", data.lifetimes)
    print("\n")
    print("observed lifetimes index:\n", data.observed())
    print("observed lifetimes values:\n", data.observed(return_values=True))
    print("\n")
    print("left censored index:\n", data.censored(how="left"))
    print("left censored values:\n", data.censored(return_values=True, how="left"))
    print("\n")
    print("right censored  index:\n", data.censored(how="right"))
    print("right censored  values:\n", data.censored(return_values=True, how="right"))
    print("\n")
    print("interval censored index:\n", data.censored(how="interval"))
    print("interval censored values:\n", data.censored(return_values=True, how="interval"))

# 1D lifetime

In [3]:
time = np.random.randint(10, high=50, size=100)
data = SurvivalData(time)
show_data(data)

     Lifetime data            Counts
              Tot.               100
          Observed               100
     Left censored                 0
    Right censored                 0
 Interval censored                 0
    Left truncated                 0
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [14 40 33 47 43 10 27 25 44 35 33 18 17 48 26 15 40 42 40 35 30 37 40 26
 39 43 42 10 14 11 45 28 35 35 41 43 45 10 28 17 39 10 35 26 11 11 12 21
 42 11 17 18 18 42 21 21 24 46 46 11 28 34 33 27 39 12 26 45 19 44 40 37
 25 29 32 38 36 41 23 19 47 28 15 39 39 22 49 14 46 39 29 37 20 25 21 20
 42 32 44 26]


observed lifetimes index:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
observed lif

In [4]:
time = np.random.randint(10, high=50, size=100)
event = np.random.randint(0, 2, size=100)
data = SurvivalData(time, event=event)
show_data(data)

     Lifetime data            Counts
              Tot.               100
          Observed                43
     Left censored                 0
    Right censored                57
 Interval censored                 0
    Left truncated                 0
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [34 27 45 31 40 32 23 19 45 34 22 48 34 31 41 16 30 26 31 33 39 16 26 40
 30 27 47 14 23 28 29 25 19 37 22 14 15 30 32 23 43 14 36 35 41 47 19 14
 15 28 47 27 21 19 43 48 10 32 27 45 13 20 30 44 29 27 47 44 41 36 11 35
 20 41 33 36 38 14 21 39 12 19 14 18 48 19 19 48 20 24 43 24 36 23 19 41
 28 46 40 35]


observed lifetimes index:
 [ 0  4  5  9 12 23 24 25 26 28 29 30 31 33 34 36 38 41 43 47 48 51 52 56
 57 58 62 64 65 66 67 70 71 72 74 75 80 83 88 89 91 95 98]
observed lifetimes values:
 [34 40 32 34 34 40 30 27 47 23 28 29 25 37 22 15 32 14 35 14 15 27 21 10
 32 27 30 29 27 47 44 11 35 20 33 36 12 18 20 24 24 41 40]


left censored index:
 []

In [5]:
print(event)

[1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1
 0 1 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 0 1 1 1 1 0 0 1 1 1 0
 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 0]


In [6]:
print(event)

[1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1
 0 1 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 0 1 1 1 1 0 0 1 1 1 0
 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 0]


In [7]:
time = np.random.randint(21, high=50, size=100)
event = np.random.randint(0, 2, size=100)
entry = np.random.randint(10, high=20, size=100)
data = SurvivalData(time, event=event, entry=entry)
show_data(data)

     Lifetime data            Counts
              Tot.               100
          Observed                50
     Left censored                 0
    Right censored                50
 Interval censored                 0
    Left truncated               100
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [42 45 31 27 46 31 35 39 40 32 24 44 25 24 26 44 45 36 42 23 26 21 28 25
 40 34 38 44 33 32 38 48 30 39 24 46 32 22 48 25 30 47 46 40 40 44 37 23
 21 48 23 27 22 32 21 45 44 35 49 34 24 26 31 33 45 43 47 27 43 32 37 40
 33 31 33 39 30 23 35 38 41 49 46 27 31 33 48 47 47 40 23 39 40 24 40 30
 26 37 39 34]


observed lifetimes index:
 [ 3  8 12 13 14 16 18 19 20 24 25 27 30 36 41 42 43 44 46 49 50 51 56 59
 60 63 64 65 66 67 68 69 71 72 73 75 76 77 78 82 84 86 87 88 89 92 94 95
 97 98]
observed lifetimes values:
 [27 40 25 24 26 45 42 23 26 40 34 44 38 32 47 46 40 40 37 48 23 27 44 34
 24 33 45 43 47 27 43 32 40 33 31 39 30 23 35 46 31 48 47 47 40

# 2D lifetime

In [8]:
time = np.array([
    [1,2],
    [0,4],
    [5,5],
    [7,np.inf],
    [10,10],
    [2,10],
    [10,11]
])
data = SurvivalData(time)
show_data(data)

     Lifetime data            Counts
              Tot.                 7
          Observed                 2
     Left censored                 1
    Right censored                 1
 Interval censored                 3
    Left truncated                 0
   Right truncated                 0
Interval truncated                 0


lifetimes:
 [[ 1.  2.]
 [ 0.  4.]
 [ 5.  5.]
 [ 7. inf]
 [10. 10.]
 [ 2. 10.]
 [10. 11.]]


observed lifetimes index:
 [2 4]
observed lifetimes values:
 [ 5. 10.]


left censored index:
 [1]
left censored values:
 [4.]


right censored  index:
 [3]
right censored  values:
 [7.]


interval censored index:
 [0 5 6]
interval censored values:
 [[ 1.  2.]
 [ 2. 10.]
 [10. 11.]]
